# Libraries

In [9]:
import os
import pandas as pd
import glob

# Compile

In [10]:
file_path = "data/*.csv"
file_list = glob.glob(file_path)
file_list

['data/zimmerman_dress_20241229_23-18-02.csv',
 'data/zimmerman_dress_20241230_17-25-09.csv',
 'data/doen_top_20241230_10-35-56.csv',
 'data/aguaByAguaBendita_skirt_20241230_10-36-06.csv',
 'data/hill_house_top_20241229_23-17-49.csv',
 'data/aguaByAguaBendita_skirt_20241229_23-17-53.csv',
 'data/zimmerman_skirt_20241229_23-18-03.csv',
 'data/hill_house_dress_20241230_10-35-59.csv',
 'data/aguaByAguaBendita_dress_20241229_23-17-50.csv',
 'data/hill_house_top_20241230_17-25-00.csv',
 'data/doen_top_20241229_23-17-42.csv',
 'data/aguaByAguaBendita_dress_20241230_10-36-04.csv',
 'data/aguaByAguaBendita_top_20241229_23-17-54.csv',
 'data/reformation_skirt_20241230_17-25-07.csv',
 'data/zimmerman_top_20241230_10-36-22.csv',
 'data/doen_skirt_20241230_10-35-58.csv',
 'data/zimmerman_top_20241230_17-25-11.csv',
 'data/doen_dress_20241230_17-24-53.csv',
 'data/reformation_skirt_20241229_23-17-58.csv',
 'data/doen_skirt_20241230_17-24-57.csv',
 'data/reformation_dress_20241230_17-25-05.csv',
 'data/reformation_dress_20241230_10-36-10.csv',
 'data/reformation_top_20241229_23-18-00.csv',
 'data/doen_dress_20241230_10-35-54.csv',
 'data/zimmerman_top_20241229_23-18-04.csv',
 'data/reformation_top_20241230_17-25-08.csv',
 'data/aguaByAguaBendita_top_20241230_10-36-08.csv',
 'data/aguaByAguaBendita_top_20241230_17-25-04.csv',
 'data/doen_dress_20241229_23-17-40.csv',
 'data/reformation_top_20241230_10-36-16.csv',
 'data/reformation_dress_20241229_23-17-56.csv',
 'data/reformation_skirt_20241230_10-36-13.csv',
 'data/doen_skirt_20241229_23-17-44.csv',
 'data/zimmerman_dress_20241230_10-36-18.csv',
 'data/hill_house_top_20241230_10-36-02.csv',
 'data/hill_house_skirt_20241230_10-36-01.csv',
 'data/aguaByAguaBendita_skirt_20241230_17-25-03.csv',
 'data/hill_house_skirt_20241230_17-24-59.csv',
 'data/zimmerman_skirt_20241230_17-25-10.csv',
 'data/hill_house_dress_20241229_23-17-46.csv',
 'data/zimmerman_skirt_20241230_10-36-20.csv',
 'data/doen_top_20241230_17-24-55.csv',
 'data/hill_house_dress_20241230_17-24-58.csv',
 'data/hill_house_skirt_20241229_23-17-47.csv',
 'data/aguaByAguaBendita_dress_20241230_17-25-01.csv']

In [11]:
df = pd.DataFrame()

for file in file_list:
    df1 = pd.read_csv(file)
    df = pd.concat([df,df1], ignore_index = True)
    
df

,title,price,size,category,style,brand,ingest_timestamp
0,zimmerman georgette dress,195.0,6,dress,NaN,zimmerman,2024-Dec-29-23:18:02
1,zimmerman,350.0,6,dress,NaN,zimmerman,2024-Dec-29-23:18:02
2,zimmerman off shoulder white 3/4 sleeves multi...,89.0,1 (4-6),dress,NaN,zimmerman,2024-Dec-29-23:18:02
3,zimmerman ready to wear wonderland floral bias...,700.0,6,dress,NaN,zimmerman,2024-Dec-29-23:18:02
4,zimmermann melody off shoulder mini dress yell...,138.0,4,dress,NaN,zimmerman,2024-Dec-29-23:18:02
...,...,...,...,...,...,...,...
1879,agua by agua bendita lima embroidered butterfl...,445.0,M,dress,NaN,aguaByAguaBendita,2024-Dec-30-17:25:01
1880,agua by agua bendita yerbamora remedios linen ...,150.0,M,dress,NaN,aguaByAguaBendita,2024-Dec-30-17:25:01
1881,agua by agua bendita habitat lima dress small,599.0,S,dress,NaN,aguaByAguaBendita,2024-Dec-30-17:25:01
1882,agua by agua bendita | naranja mimosa yellow f...,150.0,S,dress,NaN,aguaByAguaBendita,2024-Dec-30-17:25:01
1883,agua bendita lima monarca butterfly embroidere...,440.0,S,dress,NaN,aguaByAguaBendita,2024-Dec-30-17:25:01

In [12]:
df[['brand','category']].value_counts()

brand              category
aguaByAguaBendita  dress       144
                   skirt       144
                   top         144
doen               dress       144
                   skirt       144
                   top         144
hill_house         dress       144
                   skirt       144
                   top         144
reformation        dress       144
                   skirt       144
                   top         144
zimmerman          dress       129
                   top          24
                   skirt         3
Name: count, dtype: int64

# Remove Duplicates

In [13]:
[df.columns]

[Index(['title', 'price', 'size', 'category', 'style', 'brand',
        'ingest_timestamp'],
       dtype='object')]

In [14]:
df = df.sort_values(by = ['title', 'price', 'size', 'category', 'style','brand','ingest_timestamp'],
                    ascending = [True,True,True,True,True,True,False])

df = df.drop_duplicates(subset = ['title', 'price', 'size', 'category', 'style','brand'], keep = 'first')

In [15]:
df

,title,price,size,category,style,brand,ingest_timestamp
671,#49 zimmermann lace off shoulder top,66.0,6,top,NaN,zimmerman,2024-Dec-30-17:25:11
1588,*nwt agua by agua bendita - orquídea frutal az...,75.0,NaN,skirt,NaN,aguaByAguaBendita,2024-Dec-30-17:25:03
1838,agua agua bendita sucre cut-out poplin floral ...,95.0,S,dress,NaN,aguaByAguaBendita,2024-Dec-30-17:25:01
1569,agua and aguadilla milato fruit,220.0,XS,skirt,NaN,aguaByAguaBendita,2024-Dec-30-17:25:03
1549,agua bendita astro esmeralda lavanda sarong pa...,110.0,One Size,skirt,NaN,aguaByAguaBendita,2024-Dec-30-17:25:03
...,...,...,...,...,...,...,...
1240,🌹reformation top,35.0,2,top,NaN,reformation,2024-Dec-30-10:36:16
1610,🐚 nwt • hill house paz skirt in blue shell mos...,15.0,XS,skirt,NaN,hill_house,2024-Dec-30-17:24:59
573,💎 reformation hollyhock dress - ivory,200.0,Various,skirt,NaN,reformation,2024-Dec-30-17:25:07
73,💢quick flash💢zimmerman dress,35.0,2,dress,NaN,zimmerman,2024-Dec-30-17:25:09
603,💥 blow out sale 💥 nwt alexia admor maeve mini...,29.0,M,skirt,NaN,reformation,2024-Dec-30-17:25:07

# Write

In [16]:
df.to_csv("resell_prices.csv",index = False)