# Imports

In [75]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
from datetime import datetime as dt

# Doen on Poshmark

## Collect Dress Data

In [52]:
# Sold Doen Dresses
url = 'https://poshmark.com/search?query=Doen&brand%5B%5D=Doen&availability=sold_out&department=Women&category=Dresses'

response = requests.get(url)
# response.status_code
html = response.text
soup = BeautifulSoup(html, "html.parser")

In [68]:
# Dresses
dresses = [
    "Ischia", "Marianne", "Rosaria", "Lisbeth", "Wilmina",
    "Aurora", "Delphine", "Clara", "Sabine", "Odette",
    "Evelyn", "Juliette", "Amelie", "Camille", "Vera",
    "Fiona", "Nina", "Corinne", "Helene", "Lucille",
    "Margot", "Anya", "Freya", "Sylvie", "Celine",
    "Daphne", "Iris", "Luna", "Flora", "Amara",
    "Maeve", "Adelaide", "Ophelia", "Scarlett", "Viola",
    "Anastasia", "Claudia", "Elise", "Matilda", "Eloise",
    "Gwendolyn", "Ivy", "Cecilia", "Esme", "Tessa",
    "Madeleine", "Poppy", "Adele", "Serena", "Genevieve",
    "Lorraine", "Merla", "Narcisse", "Augustina", "Sabrina",
    "Alessandra", "Leyah", "Guinevere", "Francetta", "Kaira",
    "Raquella", "Pamelina", "Quinn", "Celestine", "Emmaretta",
    "Piper", "Violetta", "Noisette", "Franique", "Sera",
    "Lovisa", "Rhodia", "Gladys"
]


dresses = [x.lower() for x in dresses]
dresses = [x +' ' for x in dresses] # add a space after the name to exlude partial matches

In [ ]:
titles = soup.select(".tile__title") # listing title
prices = soup.select(".fw--bold") # sold price
sizes = soup.select(".ellipses.tile__details__pipe__size") # Size

attribs = ['title','price','size','category','style']
df = pd.DataFrame(columns = attribs)


for x in range(len(titles)):
    title = str.lower(titles[x].text.strip())
    price = float(prices[x].text.strip()[1:])
    size = sizes[x].text.strip()[6:]
    
    style = None
    for dress in dresses:
        if dress in title:
            style = dress
            break # stop after the first match 
    
    data_dict = {'title':title,
                 'price':price,
                 'size':size,
                 'category':"dress",
                 'style':style}
    
    df1 = pd.DataFrame(data_dict,index=[0])
    df = pd.concat([df,df1], axis =0,ignore_index= True)
    
df.head()

/var/folders/8p/wjrnxtq910g62m0r4449h6zr0000gn/T/ipykernel_1395/2924745510.py:27: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df,df1], axis =0,ignore_index= True)

,title,price,size,category,style
0,⚡️cco sale⚡️ doen malta floral belted corduroy...,75.0,M,dress,None
1,doen poet ruffled midi dress - black - xs,160.0,XS,dress,None
2,doen carina eyelet mini dress black - size xl,150.0,XL,dress,None
3,doen long puff sleeve maxi dress green floral ...,200.0,M,dress,None
4,doen shoulder tie floral maxi dress - size xs,100.0,XS,dress,None
5,doen victorie maxi dress in mirbeau garden flo...,200.0,M,dress,None
6,doen celestine red velvet heirloom dress nwt new,489.0,S,dress,celestine
7,doen preston liberty floral midi maxi tie wast...,200.0,M,dress,None
8,doen emmaretta floral midi maxi dress,195.0,M,dress,emmaretta
9,doen lorena dress monte isola stripe,130.0,M,dress,None
10,doen floral brown dress,126.0,S,dress,None
11,copy - doen emmaretta floral cotton midi-dress,115.0,XS,dress,emmaretta
12,doen floral maxi nwt,90.0,S,dress,None
13,doen chestnut floral dress,248.0,M,dress,None
14,new doen piper dress w optional sash belt,124.0,S,dress,piper
15,nwt dôen floral print short puff sleeve button...,200.0,M,dress,None
16,innika choo eyelet tie strap maxi dress blue s...,70.0,S,dress,None
17,doen violetta dress cream ladybird floral size xs,160.0,XS,dress,violetta
18,doen anastasia dress,380.0,XS,dress,anastasia
19,doen hollycock floral dress,218.0,M,dress,None
20,doen keira maxi dress (never worn!),120.0,M,dress,None
21,doen emmaretta floral cotton midi-dress,90.0,XS,dress,emmaretta
22,new dôen marlanna ruffled tiered silk maxi dre...,250.0,S,dress,None
23,doen floral maxi dress,150.0,S,dress,None
24,doen adele dress,100.0,4,dress,adele
25,"doen narcisse dress in camille dot, brand new ...",300.0,Various,dress,camille
26,"doen lorraine dress in emerald, brand new with...",250.0,S,dress,lorraine
27,"doen lorraine dress in emerald, brand new with...",250.0,S,dress,lorraine
28,"doen lorraine dress in emerald, brand new with...",250.0,S,dress,lorraine
29,"doen merla dress in arbor floral, size s, bran...",220.0,S,dress,merla
30,doen charleston dress in neutre jardin de papi...,90.0,XXS,dress,None
31,dôen like new rare monceau dress in blue liber...,150.0,M,dress,None
32,"doen market wrap 100% silk dress, s, great con...",75.0,S,dress,None
33,doen noisette dress,76.0,S,dress,noisette
34,doen gwendolyn silk lily of the valley maxi dr...,300.0,L,dress,gwendolyn
35,doen blue stripped button dress/cover up,145.0,M,dress,None
36,dôen joan dress in foxtail golden yellow tan o...,179.0,XS,dress,None
37,dôen franique dress in azure paris gingham nav...,170.0,XS,dress,franique
38,ischia dress in painted bouquet,280.0,M,dress,ischia
39,doen mountain dress cream california wildflowe...,250.0,M,dress,None
40,doen sera dress,140.0,L,dress,sera
41,🎀 euc! dôen lovisa 🎀 nightgown- sweet daisy pr...,172.0,XS,dress,lovisa
42,doen caico canyon burnt bloom long sleeve deep...,200.0,L,dress,None
43,doen x liberty chestnut floral dress,200.0,S,dress,None
44,doen willa floral dress,205.0,L,dress,None
45,doen plumeria off shoulder maxi dress,200.0,S,dress,None
46,new doen rhodia dress in wildflower thicket,235.0,S,dress,rhodia
47,doen gladys floral & eyelet lace dress,168.0,L,dress,gladys

In [76]:
timestamp_format = '%Y-%h-%d-%H:%M:%S'
now = dt.now()
timestamp = strftime(timestamp_format)

NameError: name 'strftime' is not defined

# Doen Product Names

In [ ]:


# Tops
tops = [
    "Henri", "Anisa", "Emiliana", "Ingrid", "Joelle",
    "Celeste", "Faye", "Gabrielle", "Juliana", "Odessa",
    "Viola", "Monique", "Sophie", "Claudine", "Elena",
    "Leona", "Paloma", "Bianca", "Marisol", "Estelle",
    "Inez", "Lorena", "Delilah", "Jocelyn", "Amara",
    "Colette", "Marielle", "Florelle", "Adeline", "Renee",
    "Sabrina", "Fleur", "Noemi", "Simone", "Vera",
    "Natalia", "Yvette", "Clarisse", "Odile", "Beatrice",
    "Camilla", "Tatiana", "Nadia", "Cleo", "Lydia",
    "Josephine", "Evelina", "Lucia", "Freya", "Marion"
]

# Skirts
skirts = [
    "Elowen", "Sebastiane", "Raina", "Beatrice", "Florence",
    "Odile", "Esther", "Giselle", "Clementine", "Simone",
    "Aurora", "Emmeline", "Coralie", "Juliet", "Isadora",
    "Felicity", "Lucia", "Vivienne", "Celestine", "Anais",
    "Noelle", "Gabriella", "Liliana", "Violette", "Rosalind",
    "Allegra", "Seraphina", "Eleanor", "Arden", "Madeleine",
    "Sophia", "Helena", "Marguerite", "Arabelle", "Isla",
    "Delphine", "Anouk", "Carys", "Evangeline", "Maris",
    "Odessa", "Viola", "Lenore", "Selene", "Camille",
    "Amelie", "Liora", "Fiona", "Adria", "Melisande"
]

# Pants
pants = [
    "Diana", "Clara", "Eloise", "Harper", "Amalia",
    "Marguerite", "Florine", "Estelle", "Genevieve", "Sabine",
    "Odessa", "Lorelei", "Miriam", "Joanna", "Lenore",
    "Viviana", "Cecile", "Delia", "Lucinda", "Aurora",
    "Francesca", "Eliana", "Isobel", "Norah", "Camille",
    "Selena", "Veronica", "Marina", "Adela", "Corinne",
    "Penelope", "Rosalyn", "Evelyn", "Jocasta", "Beatrice",
    "Cressida", "Natalia", "Florence", "Sophia", "Lyra",
    "Octavia", "Philippa", "Sabina", "Clarissa", "Giselle",
    "Ines", "Amara", "Elara", "Lucille", "Mattea"
]

# Jeans
jeans = [
    "Diana", "Harper", "Juliette", "Sienna", "Isabel",
    "Audrey", "Celeste", "Phoebe", "Emilia", "Florence",
    "Margo", "Eleanor", "Claudia", "Colette", "Bianca",
    "Anastasia", "Lena", "Amelie", "Louisa", "Monica",
    "Rosa", "Thea", "Verity", "Naomi", "Tessa",
    "Beatrix", "Delilah", "Eliza", "Helena", "Sylvia",
    "Odette", "Simone", "Freya", "Camilla", "Vera",
    "Gwen", "Margaux", "Adeline", "Clara", "Anneliese",
    "Bridget", "Catherine", "Daphne", "Elinor", "Felicity",
    "Georgina", "Hannah", "Isolde", "Jade", "Maribel"
]

# Doen

In [23]:
# Doen Dresses
url = 'https://www.shopdoen.com/collections/dresses?utm_source=google&campaign_id=10806218531&ad_id=724988960813&utm_medium=cpc&utm_campaign=actual_campaign_name_hardcoded&utm_content=104400744937&utm_term=&gclid=Cj0KCQiA4L67BhDUARIsADWrl7E0ZY9XqbDkatpsUlP50aYS24KA_m3tyCe0SNkiYI4icGTUFzKFJ7YaAoDHEALw_wcB&gad_source=1'
response = requests.get(url)

# response.status_code
html = response.text
soup = BeautifulSoup(html, "html.parser") 

elements = soup.select(".full-unstyled-link") # Size

for element in elements:
    print(element.text.strip())

AUGUSTINA DRESS
AUGUSTINA DRESS
SABRINA DRESS
ALESSANDRA DRESS
LEYAH DRESS
GUINEVERE DRESS
MERLA DRESS
CECILLIA DRESS
FRANCETTA DRESS
KAIRA DRESS
GWENDOLYN DRESS
RAQUELLA DRESS
PAMELINA DRESS
PAMELINA DRESS